stages:
  - build

build:
  stage: build
  tags:
    - lke-k8s-runner

  image: alpine/git

  script:
    - git clone https://github.com/Tae-juss/lke-gitlab-ci-demo.git
    - cd lke-gitlab-ci-demo
    - ls -la
    - cat index.html